Minimalist client side port
eBay/retriever pull request #9
Opened 2018-07-20 06:16 UTC by dsathyakumar

## Description
A client side port of `@ebay/retriever` without the dependency of `lodash.get` & `lodash.memoize`

## Context
- For minimalist use on the client side
- retains the original functions of `@ebay/retriever` and 
- re-maps via the `browser` prop.
- claws through nested data safely.

@yomed @sidsakhadeo

2018-07-20 17:43 UTC, sidsakhadeo commented
@dsathyakumar Can you publish some numbers about the performance on client without `lodash`?

2018-07-20 18:16 UTC, sidsakhadeo requested changes

2018-07-20 18:16 UTC, sidsakhadeo commented on browser.js
> +    if (typeof path === 'string') {
I'm not sure why this `if` condition would be necessary

2018-07-20 18:16 UTC, sidsakhadeo commented on browser.js
> + * @description A client side port of `@ebay/retriever`
(minor) I think you can remove this comment block. This file is self-explanatory.

2018-07-20 18:16 UTC, sidsakhadeo commented on browser.js
> + * @param {*} defaultVal - if nothing provided, defaulst to ''
(minor) `defaults` spelling

2018-07-20 18:16 UTC, sidsakhadeo commented on browser.js
> + * @param {*} defaultVal - if nothing provided, defaulst to ''
(minor) `defaults` spelling

2018-07-20 18:18 UTC, sidsakhadeo commented
@dsathyakumar @yomed I think we should have the same `test` and `perf.js` run for both server and client side code without actually duplicating the code for these in separate files. What do you think?

2018-07-20 18:20 UTC, yomed commented
@dsathyakumar Thanks for the PR, but I think we need to consider if we actually want to take this type of change. There is a lot of value in using lodash, such as 1) robustness, 2) reduced maintenance, 3) identical functionality across client and server, etc. As @sidsakhadeo mentioned, can you give more details on the benefits of this approach in general? Then if we do want to move forward, we can dig into the implementation details.

2018-07-20 19:19 UTC, sidsakhadeo commented
@dsathyakumar Also, how much is the gain in dropping `lodash` on the client side?

2018-07-23 09:32 UTC, dsathyakumar commented
Thanks @yomed @sidsakhadeo 
Before the change it was 6.2kb gzipped and now its 1.9kb gzipped.
The re-map was done to cut bytes, however, the same change could be used on the server too (thereby maintaining code uniformity). The re-map could be removed. IIRC, initial queries are fast with this change, but lodash's memoization makes repeated querying quicker.

2018-07-23 19:22 UTC, sidsakhadeo commented
> but lodash's memoization makes repeated querying quicker

I think this is useful for us. In most cases, we are querying subsections of a huge object to render templates. If repeated querying is slower, this needs to be addressed.

2018-07-24 00:44 UTC, sidsakhadeo commented
@dsathyakumar I'm guessing in the previous comment with the benchmarks, the `old` means the server side retriever calls with `lodash` and the `new` means the client side retriever calls without `lodash`. Is that correct?

2018-08-01 00:09 UTC, yomed commented
A few thoughts:
1) I'd like to avoid issues that may arise from having different implementations across server/client, especially for a case like this where it's simple to have an isomorphic solution.
2) Given the above, we should pick a single isomorphic implementation, and weigh the tradeoffs of various solutions in doing so.
3) Using an existing solution has several advantages in terms of durability and maintenance, while also allowing us to focus on the parts that make `retriever` unique (type checking, optional logging, and convenient defaults for template rendering).
4) Given that, I'm open to using other existing libraries if we believe there may be significant advantages in doing so. But I'll also say that using Lodash for this has served us well so far.

2018-08-02 18:34 UTC, dsathyakumar commented
ok! @yomed & @sidsakhadeo closing this then.
Thanks for taking time to review this 👍

2018-08-02 18:34 UTC, closed without merging